# Required
version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.8"

sphinx:
   configuration: docs/sphinx/source/conf.py

formats:
  - pdf
  - epub

python:
   install:
   - requirements: requirements.txt
